---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: {{.AWS.ClusterName}}
  namespace: {{ .TargetNamespace }}
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - "10.0.0.1/24"
    pods:
      cidrBlocks:
      - "10.0.0.2/24"
    serviceDomain: unused
