# Adds namespace to all resources.
namespace: kube-system

# Each entry in this list must resolve to an existing
# resource definition in YAML.  These are the resource
# files that kustomize reads, modifies and emits as a
# YAML string, with resources separated by document
# markers ("---").
resources:
# Install CVO clusteroperator CRD required by mao (so it can report its status)
# Pulled from https://github.com/openshift/cluster-version-operator/blob/master/install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
# and updated (delete depricated clusteroperators.operatorstatus.openshift.io CRD)
- config/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
# Install prometheus CRDs expected by mao/cao
# https://github.com/coreos/prometheus-operator/tree/ca400fdc3edd0af0df896a338eca270e115b74d7/example/prometheus-operator-crd
- config/servicemonitor.crd.yaml
- config/prometheusrule.crd.yaml
# Install feature gate CRD reguired by mao (so it can enable/disable features)
# Pulled from https://raw.githubusercontent.com/openshift/cluster-config-operator/master/manifests/0000_05_config-operator_01_featuregate.crd.yaml
- config/0000_05_config-operator_01_featuregate.crd.yaml
# Install mao namespaces, CRDS and other resources to properly deploy machine API stack
- install/0000_30_machine-api-operator_00_namespace.yaml
- install/0000_30_machine-api-operator_01_images.configmap.yaml
- install/0000_30_machine-api-operator_02_machine.crd.yaml
- install/0000_30_machine-api-operator_03_machineset.crd.yaml
- install/0000_30_machine-api-operator_07_machinehealthcheck.crd.yaml
- install/0000_30_machine-api-operator_08_baremetalhost.crd.yaml
- install/0000_30_machine-api-operator_08_machinedisruptionbudget.crd.yaml
- install/0000_30_machine-api-operator_09_rbac.yaml
- install/0000_30_machine-api-operator_10_kube-rbac-proxy-config.yaml
- install/0000_30_machine-api-operator_10_service.yaml
- config/machine-api-operator-deployment.yaml
- install/0000_30_machine-api-operator_12_clusteroperator.yaml

patches:
- config/machine-api-operator-patch.yaml
