// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineAPIOperatorConfig) DeepCopyInto(out *MachineAPIOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineAPIOperatorConfig.
func (in *MachineAPIOperatorConfig) DeepCopy() *MachineAPIOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(MachineAPIOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineAPIOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineAPIOperatorConfigList) DeepCopyInto(out *MachineAPIOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineAPIOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineAPIOperatorConfigList.
func (in *MachineAPIOperatorConfigList) DeepCopy() *MachineAPIOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(MachineAPIOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineAPIOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineAPIOperatorConfigSpec) DeepCopyInto(out *MachineAPIOperatorConfigSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineAPIOperatorConfigSpec.
func (in *MachineAPIOperatorConfigSpec) DeepCopy() *MachineAPIOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MachineAPIOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineAPIOperatorConfigStatus) DeepCopyInto(out *MachineAPIOperatorConfigStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineAPIOperatorConfigStatus.
func (in *MachineAPIOperatorConfigStatus) DeepCopy() *MachineAPIOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MachineAPIOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}
