apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-aws
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  serviceAccountNames:
  - machine-api-controllers
  secretRef:
    name: aws-cloud-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - effect: Allow
      action:
      - ec2:CreateTags
      - ec2:DescribeAvailabilityZones
      - ec2:DescribeDhcpOptions
      - ec2:DescribeImages
      - ec2:DescribeInstances
      - ec2:DescribeInstanceTypes
      - ec2:DescribeInternetGateways
      - ec2:DescribeSecurityGroups
      - ec2:DescribeRegions
      - ec2:DescribeSubnets
      - ec2:DescribeVpcs
      - ec2:RunInstances
      - ec2:TerminateInstances
      - elasticloadbalancing:DescribeLoadBalancers
      - elasticloadbalancing:DescribeTargetGroups
      - elasticloadbalancing:DescribeTargetHealth
      - elasticloadbalancing:RegisterInstancesWithLoadBalancer
      - elasticloadbalancing:RegisterTargets
      - elasticloadbalancing:DeregisterTargets
      - iam:PassRole
      - iam:CreateServiceLinkedRole
      resource: "*"
    - effect: Allow
      action:
      - kms:Decrypt
      - kms:Encrypt
      - kms:GenerateDataKey
      - kms:GenerateDataKeyWithoutPlainText
      - kms:DescribeKey
      resource: '*'
    - effect: Allow
      action:
      - kms:RevokeGrant
      - kms:CreateGrant
      - kms:ListGrants
      resource: '*'
      policyCondition:
        "Bool":
          "kms:GrantIsForAWSResource": true

---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-azure
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  serviceAccountNames:
  - machine-api-controllers
  secretRef:
    name: azure-cloud-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AzureProviderSpec
    permissions:
    - Microsoft.Compute/availabilitySets/delete
    - Microsoft.Compute/availabilitySets/read
    - Microsoft.Compute/availabilitySets/write
    - Microsoft.Compute/diskEncryptionSets/read
    - Microsoft.Compute/disks/delete
    - Microsoft.Compute/galleries/images/versions/read
    - Microsoft.Compute/skus/read
    - Microsoft.Compute/virtualMachines/delete
    - Microsoft.Compute/virtualMachines/read
    - Microsoft.Compute/virtualMachines/write
    - Microsoft.ManagedIdentity/userAssignedIdentities/assign/action
    - Microsoft.Network/applicationSecurityGroups/read
    - Microsoft.Network/loadBalancers/backendAddressPools/join/action
    - Microsoft.Network/loadBalancers/read
    - Microsoft.Network/loadBalancers/write
    - Microsoft.Network/networkInterfaces/delete
    - Microsoft.Network/networkInterfaces/join/action
    - Microsoft.Network/networkInterfaces/loadBalancers/read
    - Microsoft.Network/networkInterfaces/read
    - Microsoft.Network/networkInterfaces/write
    - Microsoft.Network/networkSecurityGroups/read
    - Microsoft.Network/networkSecurityGroups/write
    - Microsoft.Network/publicIPAddresses/delete
    - Microsoft.Network/publicIPAddresses/join/action
    - Microsoft.Network/publicIPAddresses/read
    - Microsoft.Network/publicIPAddresses/write
    - Microsoft.Network/routeTables/read
    - Microsoft.Network/virtualNetworks/delete
    - Microsoft.Network/virtualNetworks/read
    - Microsoft.Network/virtualNetworks/join/action
    - Microsoft.Network/virtualNetworks/subnets/join/action
    - Microsoft.Network/virtualNetworks/subnets/read
    - Microsoft.Resources/subscriptions/resourceGroups/read
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-openstack
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: openstack-cloud-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OpenStackProviderSpec
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-gcp
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  serviceAccountNames:
  - machine-api-controllers
  secretRef:
    name: gcp-cloud-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: GCPProviderSpec
    permissions:
    - "iam.serviceAccounts.actAs"
    - "iam.serviceAccounts.get"
    - "iam.serviceAccounts.list"
    - "compute.acceleratorTypes.get"
    - "compute.acceleratorTypes.list"
    - "compute.disks.create"
    - "compute.disks.createTagBinding"
    - "compute.disks.setLabels"
    - "compute.globalOperations.get"
    - "compute.globalOperations.list"
    - "compute.healthChecks.useReadOnly"
    - "compute.instanceGroups.create"
    - "compute.instanceGroups.delete"
    - "compute.instanceGroups.get"
    - "compute.instanceGroups.list"
    - "compute.instanceGroups.update"
    - "compute.instanceGroups.use"
    - "compute.instances.create"
    - "compute.instances.createTagBinding"
    - "compute.instances.delete"
    - "compute.instances.get"
    - "compute.instances.list"
    - "compute.instances.use"
    - "compute.instances.setLabels"
    - "compute.instances.setMetadata"
    - "compute.instances.setTags"
    - "compute.instances.setServiceAccount"
    - "compute.instances.update"
    - "compute.machineTypes.get"
    - "compute.machineTypes.list"
    - "compute.projects.get"
    - "compute.regionBackendServices.get"
    - "compute.regionBackendServices.create"
    - "compute.regionBackendServices.update"
    - "compute.regions.get"
    - "compute.regions.list"
    - "compute.subnetworks.use"
    - "compute.subnetworks.useExternalIp"
    - "compute.targetPools.addInstance"
    - "compute.targetPools.delete"
    - "compute.targetPools.get"
    - "compute.targetPools.removeInstance"
    - "compute.zoneOperations.get"
    - "compute.zoneOperations.list"
    - "compute.zones.get"
    - "compute.zones.list"
    - "resourcemanager.tagValues.get"
    - "resourcemanager.tagValues.list"
    - "serviceusage.quotas.get"
    - "serviceusage.services.get"
    - "serviceusage.services.list"

---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ovirt
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: ovirt-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OvirtProviderSpec
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-vsphere
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: vsphere-cloud-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: VSphereProviderSpec
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-ibmcloud
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudProviderSpec
    policies:
    - attributes:
      - name: serviceName
        value: is
      roles:
      - crn:v1:bluemix:public:iam::::role:Operator
      - crn:v1:bluemix:public:iam::::role:Editor
      - crn:v1:bluemix:public:iam::::role:Viewer
    - attributes:
      - name: resourceType
        value: resource-group
      roles:
      - crn:v1:bluemix:public:iam::::role:Viewer
  secretRef:
    namespace: openshift-machine-api
    name: ibmcloud-credentials
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-powervs
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: IBMCloudPowerVSProviderSpec
    policies:
      - roles:
          - "crn:v1:bluemix:public:iam::::role:Viewer"
          - "crn:v1:bluemix:public:iam::::serviceRole:Reader"
          - "crn:v1:bluemix:public:iam::::serviceRole:Manager"
        attributes:
          - name: "serviceName"
            value: "power-iaas"
      - roles:
          - "crn:v1:bluemix:public:iam::::role:Viewer"
        attributes:
          - name: "resourceType"
            value: "resource-group"
      - roles:
          - "crn:v1:bluemix:public:iam::::role:Editor"
          - "crn:v1:bluemix:public:iam::::role:Operator"
          - "crn:v1:bluemix:public:iam::::role:Viewer"
        attributes:
          - name: serviceName
            value: is
  secretRef:
    namespace: openshift-machine-api
    name: powervs-credentials
---
apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-machine-api-nutanix
  namespace: openshift-cloud-credential-operator
  annotations:
    capability.openshift.io/name: MachineAPI+CloudCredential
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  secretRef:
    name: nutanix-credentials
    namespace: openshift-machine-api
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: NutanixProviderSpec
