{
 "title": "Infra Ops Dashboard",
 "description": "Information you need about infrastructure components.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disrupted PDBs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 + (kube_poddisruptionbudget_status_pod_disruptions_allowed - on (namespace,poddisruptionbudget) 0 * (kube_poddisruptionbudget_status_desired_healthy > 0) < 1)",
     "legendFormat": "{{namespace}}/{{poddisruptionbudget}}"
    }
   ]
  },
  {
   "title": "Pod Problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max (scheduler_pending_pods{queue=\"unschedulable\"})",
     "legendFormat": "Pending Pods"
    }
   ]
  },
  {
   "title": "Machine Counts by Phase",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (phase) (mapi_machine_created_timestamp_seconds)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Node OS Image Counts",
   "type": "graph",
   "description": "Shows how many nodes of each OS image are in the cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(os_image) (kube_node_info)",
     "legendFormat": "{{os_image}}"
    }
   ]
  },
  {
   "title": "MachineSets Desired minus Available",
   "type": "graph",
   "description": "Will show difference between available replicas and desired replicas",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (mapi_machine_set_status_replicas) - on (name) (mapi_machine_set_status_replicas_available)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}