apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machinedisruptionbudgets.healthchecking.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.currentHealthy
    description: The number of healthy machines
    name: Healthy
    type: integer
  - JSONPath: .status.expectedMachines
    description: The total number of machines
    name: Total
    type: integer
  - JSONPath: .status.desiredHealthy
    description: The desired number of healthy machines
    name: Desired
    type: integer
  group: healthchecking.openshift.io
  names:
    kind: MachineDisruptionBudget
    plural: machinedisruptionbudgets
    shortNames:
    - mdb
    - mdbs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of the desired behavior of the MachineDisruptionBudget.
          properties:
            maxUnavailable:
              description: An deletion is allowed if at most "maxUnavailable" machines
                selected by "selector" are unavailable after the deletion. For example,
                one can prevent all voluntary deletions by specifying 0. This is a
                mutually exclusive setting with "minAvailable".
              format: int32
              type: integer
            minAvailable:
              description: An deletion of the machine is allowed if at least "minAvailable"
                machines selected by "selector" will still be available after the
                deletion. So for example you can prevent all voluntary deletions by
                specifying all available nodes.
              format: int32
              type: integer
            selector:
              description: Label query over machines whose deletions are managed by
                the disruption budget.
              type: object
          type: object
        status:
          description: Most recently observed status of the MachineDisruptionBudget.
          properties:
            DisruptedMachines:
              description: DisruptedMachines contains information about machines whose
                deletion was processed by the API server but has not yet been observed
                by the MachineDisruptionBudget controller. A machine will be in this
                map from the time when the API server processed the deletion request
                to the time when the machine is seen by MDB controller as having been
                marked for deletion (or after a timeout). The key in the map is the
                name of the machine and the value is the time when the API server
                processed the deletion request. If the deletion didn't occur and a
                machine is still there it will be removed from the list automatically
                by MachineDisruptionBudget controller after some time. If everything
                goes smooth this map should be empty for the most of the time. Large
                number of entries in the map may indicate problems with machines deletions.
              type: object
            currentHealthy:
              description: current number of healthy machines
              format: int32
              type: integer
            desiredHealthy:
              description: minimum desired number of healthy machines
              format: int32
              type: integer
            disruptionsAllowed:
              description: Number of machines disruptions that are currently allowed.
              format: int32
              type: integer
            expectedMachines:
              description: total number of machines counted by this disruption budget
              format: int32
              type: integer
            observedGeneration:
              description: Most recent generation observed when updating this MDB
                status. MachineDisruptionsAllowed and other status information is
                valid only if observedGeneration equals to MDB's object generation.
              format: int64
              type: integer
          required:
          - disruptionsAllowed
          - currentHealthy
          - desiredHealthy
          - expectedMachines
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
