apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: machineclasses.cluster.k8s.io
spec:
  group: cluster.k8s.io
  names:
    kind: MachineClass
    plural: machineclasses
  scope: Namespaced
  validation:
    openAPIV3Schema:
      anyOf:
      - properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          providerSpec:
            type: object
        required:
        - providerSpec
      - properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          providerConfig:
            type: object
        required:
        - providerConfig
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
