apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: machine-api-operator-prometheus-rules
  namespace: openshift-machine-api
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  groups:
    - name: machine-without-valid-node-ref
      rules:
        - alert: MachineWithoutValidNode
          expr: |
             sum by (name, namespace) (mapi_machine_created_timestamp_seconds unless on(node) kube_node_info) > 0
          for: 60m
          labels:
            severity: warning
          annotations:
            summary: "machine {{ $labels.name }} does not have valid node reference"
            description: |
              If the machine never became a node, you should diagnose the machine related failures.
              If the node was deleted from the API, you may delete the machine if appropriate.
    - name: machine-with-no-running-phase
      rules:
        - alert: MachineWithNoRunningPhase
          expr: |
            sum by (name, namespace) (mapi_machine_created_timestamp_seconds{phase!~"Running|Deleting"}) > 0
          for: 60m
          labels:
            severity: warning
          annotations:
            summary: "machine {{ $labels.name }} is in phase: {{ $labels.phase }}"
            description: |
              The machine has been without a Running or Deleting phase for more than 60 minutes.
              The machine may not have been provisioned properly from the infrastructure provider, or
              it might have issues with CertificateSigningRequests being approved.
    - name: machine-not-yet-deleted
      rules:
        - alert: MachineNotYetDeleted
          expr: |
            sum by (name, namespace) (avg_over_time(mapi_machine_created_timestamp_seconds{phase="Deleting"}[15m])) > 0
          for: 360m
          labels:
            severity: warning
          annotations:
            summary: "machine {{ $labels.name }} has been in Deleting phase for more than 6 hours"
            description: |
              The machine is not properly deleting, this may be due to a configuration issue with the
              infrastructure provider, or because workloads on the node have PodDisruptionBudgets or
              long termination periods which are preventing deletion.
    - name: machine-api-operator-metrics-collector-up
      rules:
        - alert: MachineAPIOperatorMetricsCollectionFailing
          expr: |
             mapi_mao_collector_up == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "machine api operator metrics collection is failing."
            description: "For more details:  oc logs <machine-api-operator-pod-name> -n openshift-machine-api"
    - name: machine-health-check-unterminated-short-circuit
      rules:
        - alert: MachineHealthCheckUnterminatedShortCircuit
          expr: |
            mapi_machinehealthcheck_short_circuit == 1
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "machine health check {{ $labels.name }} has been disabled by short circuit for more than 30 minutes"
            description: |
              The number of unhealthy machines has exceeded the `maxUnhealthy` limit for the check, you should check
              the status of machines in the cluster.
